### ISSUE TITLE
Unclear error message when __generated__ folder is missing

### ISSUE THREAD

**Issue by youngkidwarrior** [zth/resgraph#24]
If the folder defined in `resgraph.json` doesn't exist, ResGraph fails to compile. 

This is the error message if `/src/schema/__generated__` doesn't exist:

```
Error: Command failed: /path/to/repo/node_modules/resgraph/bin/darwin/resgraph.exe generate-schema
  /path/to/repo/src  /path/to/repo/src/schema/__generated__ true
```

This error could be a common mistake for new users and the message could be improved

**Comment by zth** [comment]
Fixed in https://github.com/zth/resgraph/commit/3e404b01758e02c41b4b3c6b312a8c73e6cf1d27.
